# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestWeakLinking' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
#  use_frameworks! :linkage => :static

  # Pods for TestWeakLinking
  pod 'WeakLinkingPOCSDK', :path => '../weakLinkingPOC'
#  pod 'AlonSourcesSDK'
#  pod 'OptionalFrameworkSDK', :path => '../OptionalFramework'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if target.name == "SourcesSDK" || target.name == "OptionalFrameworkSDK"
        config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      end
    end
  end
end
